# Generated by Django 5.2.6 on 2025-09-06 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_email', models.EmailField(db_index=True, max_length=50, unique=True)),
                ('business_name', models.CharField(max_length=100)),
                ('tax_id', models.CharField(max_length=15, unique=True, verbose_name='VÖEN')),
                ('password', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('active_session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='businessuser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='businessuser_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Biznes İstifadəçisi',
                'verbose_name_plural': 'Biznes İstifadəçiləri',
            },
        ),
        migrations.CreateModel(
            name='BusinessUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Nömrəsi')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ölkə')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Əyalət / Bölgə')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şəhər')),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ünvan 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ünvan 2 (istəyə bağlı)')),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Poçt Kodu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə olunma tarixi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biznes İstifadəçi Profili',
                'verbose_name_plural': 'Biznes İstifadəçi Profilləri',
            },
        ),
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=250)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Token',
                'verbose_name_plural': 'OTP Tokens',
            },
        ),
    ]
